name: deloy-auth

on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t ngquangan/ticketing-auth .
      - run: docker login -u $DOCKER_PASSWORD -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ngquangan/ticketing-auth
